### ISSUE TITLE
Embeddings Generation

### ISSUE THREAD

**Issue by abhigoku10** [mshenoda/diffugen#2]
@mshenoda  how to train the model present int he embedding folder , what significance does it have can we train it to get for bikes , people with different view points 

THanks in adavnce

**Comment by mshenoda** [comment]
Textual inversion is a training technique used in the context of stable diffusion models. It allows you to add new styles or objects to your text-to-image models without modifying the underlying model. This technique works by learning and updating the text embeddings to match the example images you provide.

Here is how it works, generally speaking: 

- A new keyword representing the desired concept is defined with a place holder <keyword>.
- A new embedding vector for this specific word or token is initialized.
- A collection of images that represent the new style or object is provided.
- The new embedding vector is trained with these images to represent the desired concept in the embedding space.
- The trained embeddings are loaded into the existing model. The model itself is not retrained.
- The model generates images that aligns with the desired concept keyword using the new embeddings.

To train the textual inversion embedding, please follow this notebook:  https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers_doc/en/pytorch/text_inversion.ipynb
